baseURL = "https://aringadre76.github.io/"
title = "Arin Gadre"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"

# Replace the old paginate with the new pagination config
[pagination]
  pagerSize = 20

# Add markup configuration to allow raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Add this to suppress the HTML warnings
[params]
  ignoreLogs = ['warning-goldmark-raw-html']

# Social links
[[params.social]]
name = "Email"
icon = "fa fa-envelope fa-2x"
weight = 1
url = "mailto:aringadre@gmail.com"
target = "_self"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://github.com/aringadre76"
target = "_blank"
rel = "noopener noreferrer"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/arin-gadre/"
target = "_blank"
rel = "noopener noreferrer"

# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[menu.main]]
name = "Experience"
weight = 3
url = "experience/"

[[menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[[menu.main]]
name = "Resume"
weight = 5
url = "/resume.pdf"
target = "_blank"
rel = "noopener"

[params.style]
primaryColor = "#ff2e88"
secondaryColor = "#00fff5"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1 